#!/usr/bin/env zsh

# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
function fzf-down() {
  fzf --height 50% "$@" --border
}

fzf-down

# Local Variables:
# mode: shell-script
# End:
