#!/usr/bin/env zsh

# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
function gb() {
  is-in-git-repo || return
  git branch -a --color=always | grep -v '/HEAD\s' | sort |
  fzf-down --ansi --multi --tac --preview-window right:70% \
    --preview 'git log --oneline --graph --date=short --color=always --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} | cut -d" " -f1) | head -'$LINES |
  sed 's/^..//' | cut -d' ' -f1 |
  sed 's#^remotes/##'
}

gb

# Local Variables:
# mode: shell-script
# End:
