#!/usr/bin/env zsh

function emacs-client () {
  if [ -z "${@}" ]; then
    # There are no arguments, so tell Emacs to open a new window
    emacsclient -c --eval "(dired \"$(pwd)\")" &
  else
    # Try to open the file provided as an argument in an existing Emacs client.
    emacsclient "${@}" &
  fi

  emacsclient --eval "(x-focus-frame (selected-frame))"
}

emacs-client "${@}"

# Local Variables:
# mode: shell-script
# End:
