#!/usr/bin/env zsh

function run-emacs() {
  if isdarwin; then
    "$(dirname $(dirname $(readlink -f $(whence emacs))))/Applications/Emacs.app/Contents/MacOS/Emacs" "${@}";
  else
    run-emacs "${@}"
  fi;
}

run-emacs "${@}"
